### ISSUE TITLE
[Issue]: ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Invalid value  for configuration value.serializer: Class could not be found. org.apache.kafka.common.config.ConfigException: Invalid value  for configuration value.serializer: Class  could not be found.

### ISSUE THREAD

**Issue by whaleist** [sngular/kloadgen#320]
### What happened?

Hello,
I'm trying to use KLoadGen plugin with jmeter (AVRO scheme) and getting an error.
My test plan is similar to https://github.com/corunet/kloadgen/blob/master/Example-Test-Plan-2.jmx except the connection and the scheme (but as I see, the issue is not in the scheme as when I try to use the sample scheme I get the same error too)

### KloadGen Version

5.1.3

### Relevant log output

```shell
2022-12-19 12:32:48,937 ERROR o.a.j.p.j.s.AbstractJavaSamplerClient: Invalid value  for configuration value.serializer: Class  could not be found.
org.apache.kafka.common.config.ConfigException: Invalid value  for configuration value.serializer: Class  could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:728) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:474) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:467) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:108) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:129) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.clients.producer.ProducerConfig.<init>(ProducerConfig.java:481) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:326) ~[di-kafkameter-1.0.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:298) ~[di-kafkameter-1.0.jar:?]
	at net.coru.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:83) [kloadgen-5.1.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) [ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-12-19 12:32:48,939 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer Properties'.
java.lang.NullPointerException: Cannot invoke "org.apache.kafka.clients.producer.KafkaProducer.send(org.apache.kafka.clients.producer.ProducerRecord, org.apache.kafka.clients.producer.Callback)" because "this.producer" is null
	at net.coru.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:141) ~[kloadgen-5.1.3.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:638) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:558) ~[ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:489) [ApacheJMeter_core.jar:5.4.3]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:256) [ApacheJMeter_core.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by whaleist** [comment]
[ExampleTP.txt](https://github.com/corunet/kloadgen/files/10258297/ExampleTP.txt)
[schema.txt](https://github.com/corunet/kloadgen/files/10258301/schema.txt)

**Comment by mseijasm** [comment]
Hi @whaleist,

Thank you for your collaboration. 
This wednesday we will do a migration of the project to another domain on Github. As soon as we complete it, we will start with this issue.

**Comment by rabad-sng** [comment]
Hi @whaleist,

Could you retry running [Example-Test-Plan-2.jmx](https://github.com/sngular/kloadgen/blob/master/Example-Test-Plan-2.jmx) included in latest version? Also, we would be grateful if you could share the results of running your own test plans.

Thank you!

**Comment by AdrianLagarteraSngular** [comment]
Closed due to lack of response and without having received a similar error in several months.
