### ISSUE TITLE
[Issue]: Schema registry URL field not recognized when running Kafka Producer with Apicurio

### ISSUE THREAD

**Issue by hpasaricekCROZ** [sngular/kloadgen#381]
### What happened?

Hello,

I have a problem when running **Kafka Producer tests with connection to Apicurio schema registry.**
I configured all the neccessary fields in my Kafka Producer and Apicurio Schema Registry Config Element.

The problem is that when I try to run the test, the program throws an error that the field **schema.registry.url is not defined** even though I entered the URL of the schema registry. 

![image](https://github.com/sngular/kloadgen/assets/131460727/39833f72-1a03-4dbb-b2a1-5b77b192d6eb)

Can you please check and let me know?

Schema and test plan attached.
[KafkaProducerTest.zip](https://github.com/sngular/kloadgen/files/11496469/KafkaProducerTest.zip)

P.S. I was playing around with your source code a bit and managed to make a (pretty crude) hotfix that saves the schema.registry.url to the configuration and that part works now but I encountered two more issues after fixing that. When you check this issue mentioned above please let me know so I can check if these two issues persist after your official fix.

### KloadGen Version

KloadGen 5.6.0.

### Relevant log output

```shell
org.apache.kafka.common.KafkaException: Failed to construct kafka producer
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:442) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:292) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:319) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:304) ~[kloadgen-5.6.0-original.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:100) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
Caused by: org.apache.kafka.common.config.ConfigException: Missing required configuration "schema.registry.url" which has no default value.
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:493) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:133) ~[kloadgen-5.6.0-original.jar:?]
	at io.confluent.kafka.serializers.AbstractKafkaSchemaSerDeConfig.<init>(AbstractKafkaSchemaSerDeConfig.java:211) ~[kloadgen-5.6.0-original.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializerConfig.<init>(KafkaAvroSerializerConfig.java:56) ~[kloadgen-5.6.0-original.jar:?]
	at io.confluent.kafka.serializers.KafkaAvroSerializer.configure(KafkaAvroSerializer.java:50) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.kafka.clients.producer.KafkaProducer.<init>(KafkaProducer.java:378) ~[kloadgen-5.6.0-original.jar:?]
	... 10 more
2023-05-17 11:32:49,028 INFO o.a.j.s.SampleResult: Note: Sample TimeStamps are START times
2023-05-17 11:32:49,028 INFO o.a.j.s.SampleResult: sampleresult.default.encoding is set to ISO-8859-1
2023-05-17 11:32:49,028 INFO o.a.j.s.SampleResult: sampleresult.useNanoTime=true
2023-05-17 11:32:49,029 INFO o.a.j.s.SampleResult: sampleresult.nanoThreadSleep=5000
2023-05-17 11:32:49,043 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer'.
java.lang.NullPointerException: null
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:149) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-05-17 11:32:49,044 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer'.
java.lang.NullPointerException: null
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:149) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-05-17 11:32:49,045 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Producer'.
java.lang.NullPointerException: null
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:149) ~[kloadgen-5.6.0-original.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:829) ~[?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by AdrianLagarteraSngular** [comment]
Hi @hpasaricekCROZ 
Thanks for collaborate again, I'll take a look at the problems you mention and let you know as soon as we have a fix.

**Comment by AdrianLagarteraSngular** [comment]
@hpasaricekCROZ Sorry for the delay, I just uploaded a small change to the branch linked to the issue, using your schema, and your test plan makes it work, to take into consideration in my case I used an unsecured Kafka, it should not influence but just to have it in case the fix provided does not solve the problem.

Let me know if it works for you, thank you very much

**Comment by hpasaricekCROZ** [comment]
@AdrianLagarteraSngular Hi, I tested your fix and the **original error where schema.registry.url was not found is now solved** but another error is now hapenning.

As far as I can tell, for the property **schema.registry.url** you are using the field that is defined in **Schema Registry Confing Element** -> **Schema Registry URL**?

![image](https://github.com/sngular/kloadgen/assets/131460727/4e8faddc-346f-411b-84f2-41ec321cd05d)

You are not using the field that is defined **Java Request** -> **Kafka Producer Sampler** -> **schema.registry.url**?
I tried leaving that field empty and I can see that the URL is being fetched from the Schema Registry Config Element.

![image](https://github.com/sngular/kloadgen/assets/131460727/f5236ecf-e217-4267-9b17-56599fcaf60d)

**Comment by AdrianLagarteraSngular** [comment]
Hi @hpasaricekCROZ as you have seen, we have that property duplicated, the mandatory is the **Config Element  -> Schema Registry URL**, the other is a property that has been left from older versions where the configuration to different registry schemas was not yet implemented.

So it is not a bug as such, but it is necessary a small refactor to remove those obsolete or moved properties.

Once again, thank you for providing information on the errors you have been able to verify.
