### ISSUE TITLE
[Issue]: JSON value shema serializer exception

### ISSUE THREAD

**Issue by CROprogrammer** [sngular/kloadgen#423]
### What happened?

I've created a simple test plan that sends messages with key of type string, and value of type JSON. And when I try to send message to topic, I get an exception as shown below. I do not import schema, but I define it in KLoadGen by hand, because I do not want to use Schema Registry. I get this exception for any JSON serializer.

JMX: 
[Simple Test Plan.zip](https://github.com/sngular/kloadgen/files/13389850/Simple.Test.Plan.zip)

### KloadGen Version

5.6.6

### Relevant log output

```shell
2023-11-17 10:14:15,931 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Java Request'.
com.sngular.kloadgen.exception.KLoadGenException: Unsupported Serializer
	at com.sngular.kloadgen.sampler.SamplerUtil.getLoadGenerator(SamplerUtil.java:482) ~[kloadgen-5.6.6.jar:?]
	at com.sngular.kloadgen.sampler.SamplerUtil.configureValueGenerator(SamplerUtil.java:363) ~[kloadgen-5.6.6.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:76) ~[kloadgen-5.6.6.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) ~[ApacheJMeter_core.jar:5.5]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) ~[ApacheJMeter_core.jar:5.5]
	at java.lang.Thread.run(Thread.java:1623) ~[?:?]
2023-11-17 10:14:15,932 INFO o.a.j.t.JMeterThread: Thread is done: Thread Group 1-1
2023-11-17 10:14:15,932 INFO o.a.j.t.JMeterThread: Thread finished: Thread Group 1-1
2023-11-17 10:14:15,932 INFO o.a.j.e.StandardJMeterEngine: Notifying test listeners of end of test
2023-11-17 10:14:15,932 INFO o.a.j.g.u.JMeterMenuBar: setRunning(false, *local*)
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by jemacineiras** [comment]
Hi @CROprogrammer,

This is a know issue which is currently under solution. Will inform here when the fix is ready.

Cheers
