### ISSUE TITLE
[Issue]: Error while processing sampler: 'Kafka Broker'. java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "registry" is null

### ISSUE THREAD

**Issue by xck1007** [sngular/kloadgen#428]
### What happened?

I get nullpointer exceptions when calling the kafka broker (java request). I can call the schema registry on a test basis. I can call the key schema und the value schema. But the java request (Kafka Broker) receives errors. 
[Error.zip](https://github.com/sngular/kloadgen/files/13645535/Error.zip)

### KloadGen Version

my built version 5.6.11 on the basis of 5.6.7 

### Relevant log output

```shell
2023-12-12 09:00:10,548 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Broker'.
java.lang.NullPointerException: Cannot invoke "String.toUpperCase()" because "registry" is null
	at com.sngular.kloadgen.schemaregistry.SchemaRegistryManagerFactory.getSchemaRegistry(SchemaRegistryManagerFactory.java:22) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.loadgen.impl.SRLoadGenerator.retrieveSchema(SRLoadGenerator.java:20) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.loadgen.impl.AvroSRLoadGenerator.setUpGenerator(AvroSRLoadGenerator.java:38) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.sampler.SamplerUtil.configureKeyGenerator(SamplerUtil.java:456) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.setupTest(KafkaProducerSampler.java:83) ~[kloadgen-5.6.11.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194) ~[ApacheJMeter_java.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) [ApacheJMeter_core.jar:5.6.2]
	at java.lang.Thread.run(Thread.java:833) [?:?]


2023-12-12 09:00:10,577 ERROR o.a.j.t.JMeterThread: Error while processing sampler: 'Kafka Broker'.
java.lang.NullPointerException: Cannot invoke "java.util.Collection.toArray()" because "c" is null
	at java.util.ArrayList.<init>(ArrayList.java:181) ~[?:?]
	at com.sngular.kloadgen.randomtool.util.ValueUtils.replaceValuesContext(ValueUtils.java:28) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.randomtool.generator.StatelessGeneratorTool.generateObject(StatelessGeneratorTool.java:38) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.getProducerRecord(KafkaProducerSampler.java:176) ~[kloadgen-5.6.11.jar:?]
	at com.sngular.kloadgen.sampler.KafkaProducerSampler.runTest(KafkaProducerSampler.java:138) ~[kloadgen-5.6.11.jar:?]
	at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:197) ~[ApacheJMeter_java.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570) ~[ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501) [ApacheJMeter_core.jar:5.6.2]
	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268) [ApacheJMeter_core.jar:5.6.2]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

### Have you added your JMX Testplan or a replica?

- [X] I have added a JMX testplan

### Have you added your Schema or a replica?

- [X] I have added the Schema

**Comment by xck1007** [comment]
Can someone please help me here.

**Comment by AdrianLagartera** [comment]
Could you add the jmx without the Prometheus plugin part to give it a look?

**Comment by jemacineiras** [comment]
This is really odd and sad. Still do not know why is failing to your setup since we aree working in the latest for a while. 
Can you please attach your full configuration, SO, JDK version, plugins you have installed and a sample JMX. I will try to replcate your setup in order to solve your issue.

Cheers

**Comment by xck1007** [comment]
I am using JMeter 5.6.2, Windows 10, Java 17.0.3.1, kloadgen 5.6.10 (from https://mvnrepository.com/artifact/com.sngular/kloadgen/5.6.10). I have uploaded the JMX file, jmeter.log, property files and a screenshot with a list of the plugins in a ZIP file. 

I also had the errors based on kloadgen 5.6.7 (I built a version myself because the one provided had dependency errors).

If you need anything else to analyse, just let me know. Thank you very much for looking at this :-)

[kloadgen-error.zip](https://github.com/sngular/kloadgen/files/14021060/kloadgen-error.zip)

**Comment by xck1007** [comment]
The same error occurs on Ubuntu Linux 22.04 as well. Is there any way I can assist in resolving the issue?

**Comment by jemacineiras** [comment]
We had tried to reproduce in the same O.S. and versions and we could not see it failing. For all of us is working like a charm. Is there any other way you can send to us. 
Let me try to generate a versión with specific debug messages and I will let here the link.

**Comment by xck1007** [comment]
I have downloaded JMeter version 5.6.2 and kloadgen 5.6.11 again. Nothing else. I still get the error. I can use the button "Test Registry", press the button "Load Subject" at Key Schema and Value Schema, everything is ok. Only when I start the load test do I get the reported errors.

I am now completely at a loss!?!? 

[jmeter.log](https://github.com/sngular/kloadgen/files/14237577/jmeter.log)

**Comment by xck1007** [comment]
Sorry, i meant kloadgen 5.6.10.

[jmeter.log](https://github.com/sngular/kloadgen/files/14237690/jmeter.log)

**Comment by sushmatshetty** [comment]
@xck1007 did u get a solution for this
